### ISSUE TITLE
Add external supporters page

### ISSUE THREAD

**Issue by kenodressel** [option26/quarantine-hero#217] opened 2020-04-08 17:08 UTC
the page should feature:
- organizations that support quarantaenehelden with resources
- friendly organizations that offer good services / resources related to corona
- individuals who supported us

**Comment by tgraupne** [comment] 2020-04-15 16:58
We are currently still in discussion with the GroßTeam about the design, content and specific use-case of this page.

**Comment by Maurice22** [comment] 2020-04-26 17:55
Is currently conceptualized. Once this is done we will implement it.

**Comment by mauriceackel** [comment] 2020-06-26 19:50
Duplicate of #315 
Closing now.

**Closed by mauriceackel** 2020-06-26 19:50 UTC
Labels: enhancement, needs consideration, priority-low, waiting for feedback
